@ stdcall BTCpuFlushInstructionCache2(ptr long)
@ stdcall BTCpuFlushInstructionCacheHeavy(ptr long)
@ stdcall BTCpuGetBopCode()
@ stdcall BTCpuGetContext(long long ptr ptr)
@ stdcall BTCpuIsProcessorFeaturePresent(long)
@ stdcall BTCpuNotifyMapViewOfSection(ptr ptr ptr long long long)
@ stdcall BTCpuNotifyMemoryAlloc(ptr long long long long long)
@ stdcall BTCpuNotifyMemoryDirty(ptr long)
@ stdcall BTCpuNotifyMemoryFree(ptr long long long long)
@ stdcall BTCpuNotifyMemoryProtect(ptr long long long long)
@ stdcall BTCpuNotifyProcessExecuteFlagsChange(long)
@ stdcall BTCpuNotifyReadFile(ptr ptr long long long)
@ stdcall BTCpuNotifyUnmapViewOfSection(ptr long long)
@ stdcall BTCpuProcessInit()
@ stdcall BTCpuProcessTerm(ptr long long)
@ stdcall BTCpuResetToConsistentState(ptr)
@ stdcall BTCpuSetContext(long long ptr ptr)
@ stdcall -norelay BTCpuSimulate()
@ stdcall BTCpuThreadInit()
@ stdcall BTCpuThreadTerm(ptr long)
@ stdcall BTCpuTurboThunkControl(long)
@ stdcall BTCpuUpdateProcessorInformation(ptr)
@ stdcall __wine_get_unix_opcode()
